### ISSUE TITLE
[HW6] MAC и IP адреса, планирование подсетей и DNS

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Eugene-stasiukevich#6]
**Дедлайн: 03/08/2023**<br /><br />1. Определить все IP адреса, маски подсетей и соответствующие MAC адреса Linux VM. Определите класс и адреса подсетей, в которых находится VM.<br />2. Определить публичный IP адрес хоста и Linux VM? Чем они отличаются?<br />3. Вывести ARP таблицу на хосте и найти там запись, соответствующую MAC адресу с предыдущего задания. Если её нет, то объяснить почему.<br />4. Выполнить разбиение сети 172.20.0.0/16 на подсети с маской /24 и ответить на следующие вопросы:<br />    - Сколько всего подсетей будет в сети?<br />    - Сколько узлов будет в каждой подсети?<br />    - Каким будет сетевой адрес первой и второй подсети?<br />    - Каким будут адреса первого и последнего хостов в первой и второй подсетях?<br />    - Каким будет широковещательный адрес в последней подсети?<br />5. Найти IP адрес соответствующий доменному имени ya.ru. Выполнить HTTP запрос на указанный IP адрес, чтобы скачать страницу с помощью утилиты curl. В результате должна вывестись HTML страничка в консоль. Подсказка: https://stackoverflow.com/questions/46563730/can-i-access-to-website-using-ip-address

**Comment by Infectdream** [comment]
@AlexPykavy как будет время, посмотри пожалуйста :)
В 5-м задании по ip не хотел ничего выводить, может нужно с сертификатами поиграть? Но я пока не нашёл как с ними правильно обращаться

**Comment by AlexPykavy** [comment]
В 5-м задании нужно передать заголовок `Host` при обращении по IP.

**Comment by Infectdream** [comment]
@AlexPykavy проверь пожалуйста, как будет время)

**Comment by AlexPykavy** [comment]
Принимается!
